# Generated by Django 6.0.3 on 2026-04-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0028_forecasts_mean_forecasts_stdev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAgileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('agile_pred', models.FloatField()),
                ('agile_low', models.FloatField()),
                ('agile_high', models.FloatField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_prices', to='prices.forecasts')),
            ],
            options={
                'unique_together': {('forecast', 'date_time')},
            },
        ),
    ]
