# Generated by Django 6.0.3 on 2026-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0029_officialagiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('gas_price_ptherm', models.FloatField()),
                ('carbon_price_eur', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
